### ISSUE TITLE
Array-hinted parameters with default value of []

### ISSUE THREAD

**Issue by assertchris** [textmate/php.tmbundle#54]
The following default value is displayed as a syntax error:

```php
function foo(array $args = []) {
    // ...
}
```

**Comment by infininight** [comment]
Corrected in 5d9b5d0d6eb9a4779aa02404ba733a2ff4fc955e, thanks for the report.

**Comment by graymalkin** [comment]
:beers: 
Awesome work -- that bug was very annoying.

**Comment by JackBlower** [comment]
Excellent thanks. =D

:+1:

**Comment by franzliedke** [comment]
The [old syntax](https://github.com/Riari/laravel-forum/blob/master/src/Riari/Forum/Repositories/Threads.php) still appears to be broken.

**Comment by infininight** [comment]
@franzliedke It works if you lowercase the array:

```php
<?php 

public function getByID($threadID, array $with = array()) {}

?>
```
